const $=id=>document.getElementById(id);const refs=['assets/flower_black_dahlia.jpg'];let songs=[{id:'1',title:'BLACK DAHLIA',artist:'Luna Noire',album:'Dark Bloom EP',duration:240,img:refs[0],src:'',favorite:false,played:0},{id:'2',title:'MIDNIGHT PULSE',artist:'K. Vex',album:'Neon Nights',duration:178,img:refs[0],src:'',favorite:false,played:0},{id:'3',title:'GOLDEN HOUR',artist:'Atlas Echo',album:'Golden Hour',duration:252,img:refs[0],src:'',favorite:false,played:0},{id:'4',title:'VELVET SKIES',artist:'Luna Noire',album:'Afterglow',duration:214,img:refs[0],src:'',favorite:false,played:0}];let current=0,shuffle=false,repeat=false,searchType='all',demoPlaying=false;const audio=$('audio');const fmt=s=>{s=Math.max(0,Math.floor(s||0));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};const setArt=(e,u)=>e.style.backgroundImage=`url("${u}")`;
function render(list,target){$(target).innerHTML=list.map(s=>`<article class="song-card" data-id="${s.id}"><div class="art"></div><div class="song-info"><b>${s.title}</b><span>${s.artist} • ${fmt(s.duration)} • ${s.album}</span></div><div class="song-actions"><button class="play">▶</button><button class="fav">${s.favorite?'♥':'♡'}</button></div></article>`).join('')||'<div class="empty">No songs found.</div>';$(target).querySelectorAll('.song-card').forEach(c=>{let s=songs.find(x=>x.id===c.dataset.id);setArt(c.querySelector('.art'),s.img);c.querySelector('.play').onclick=e=>{e.stopPropagation();playSong(s.id,true)};c.querySelector('.fav').onclick=e=>{e.stopPropagation();toggleFav(s.id)};c.onclick=()=>playSong(s.id,true)})}
function renderAll(){render(songs,'trending');render(songs,'searchResults');render(songs,'libraryList');updateStats()}function setUI(s){['miniArt','disc','bannerArt'].forEach(id=>setArt($(id),s.img));$('miniTitle').textContent=s.title;$('miniArtist').textContent=s.artist;$('nowTitle').textContent=s.title;$('nowArtist').textContent=`${s.artist} • ${s.album}`;$('timeTotal').textContent=fmt(s.duration);$('mLike').textContent=s.favorite?'♥':'♡'}function playSong(id,open){let i=songs.findIndex(s=>s.id===id);if(i<0)return;current=i;let s=songs[current];setUI(s);s.played++;updateStats();demoPlaying=false;if(s.src){audio.src=s.src;audio.currentTime=0;audio.play().catch(()=>{})}else audio.removeAttribute('src');if(open)$('player').classList.add('open');updatePlayButtons()}
function toggle(){let s=songs[current];if(s.src){audio.paused?audio.play().catch(()=>{}):audio.pause()}else{demoPlaying=!demoPlaying;updatePlayButtons()}}function updatePlayButtons(){let on=songs[current].src?!audio.paused:demoPlaying;$('mPlay').textContent=on?'Ⅱ':'▶';$('pPlay').textContent=on?'Ⅱ':'▶'}function next(){let i=shuffle?Math.floor(Math.random()*songs.length):(current+1)%songs.length;playSong(songs[i].id,false);if(!songs[i].src){demoPlaying=true;updatePlayButtons()}}function prev(){if(audio.currentTime>5){audio.currentTime=0;return}let i=(current-1+songs.length)%songs.length;playSong(songs[i].id,false);if(!songs[i].src){demoPlaying=true;updatePlayButtons()}}function toggleFav(id){let s=songs.find(x=>x.id===id);s.favorite=!s.favorite;renderAll();if(s.id===songs[current].id)setUI(s)}function show(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(p).classList.add('active');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===p))}function search(){let q=$('searchInput').value.toLowerCase().trim();let list=songs.filter(s=>{if(searchType==='song')return s.title.toLowerCase().includes(q);if(searchType==='artist')return s.artist.toLowerCase().includes(q);if(searchType==='album')return s.album.toLowerCase().includes(q);return `${s.title} ${s.artist} ${s.album}`.toLowerCase().includes(q)});render(list,'searchResults')}function updateStats(){$('favCount').textContent=songs.filter(s=>s.favorite).length;$('songCount').textContent=songs.length;$('recentCount').textContent=songs.filter(s=>s.played>0).length}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>show(b.dataset.page));$('homeBtn').onclick=()=>show('home');$('openSearch').onclick=()=>{show('search');$('searchInput').focus()};$('seeAll').onclick=()=>{show('search');$('searchInput').focus()};$('continueBtn').onclick=()=>playSong(songs[current].id,true);$('randomBtn').onclick=()=>{shuffle=true;next();$('player').classList.add('open')};$('bannerPlay').onclick=()=>playSong('1',true);$('mPlay').onclick=toggle;$('pPlay').onclick=toggle;$('mNext').onclick=next;$('pNext').onclick=next;$('mPrev').onclick=prev;$('pPrev').onclick=prev;$('closePlayer').onclick=()=>$('player').classList.remove('open');$('mini').ondblclick=()=>$('player').classList.add('open');$('miniArt').onclick=()=>$('player').classList.add('open');$('mLike').onclick=()=>toggleFav(songs[current].id);$('shuffle').onclick=()=>{shuffle=!shuffle;$('shuffle').style.opacity=shuffle?1:.45};$('repeat').onclick=()=>{repeat=!repeat;$('repeat').style.opacity=repeat?1:.45};$('playerLibrary').onclick=()=>{$('player').classList.remove('open');show('library')};$('volume').oninput=e=>audio.volume=e.target.value/100;$('seek').oninput=e=>{if(audio.src)audio.currentTime=+e.target.value};audio.ontimeupdate=()=>{$('seek').max=audio.duration||songs[current].duration;$('seek').value=audio.currentTime;$('timeNow').textContent=fmt(audio.currentTime);$('timeTotal').textContent=fmt(audio.duration||songs[current].duration)};audio.onplay=updatePlayButtons;audio.onpause=updatePlayButtons;audio.onended=()=>repeat?(audio.currentTime=0,audio.play()):next();$('searchInput').oninput=search;document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');searchType=c.dataset.type;search()});document.querySelectorAll('.library-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.library-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');let t=b.dataset.lib,list=t==='favorites'?songs.filter(s=>s.favorite):t==='recent'?songs.filter(s=>s.played>0):t==='uploads'?songs.filter(s=>s.src):songs;render(list,'libraryList')});$('audioFiles').onchange=e=>{[...e.target.files].forEach(f=>songs.push({id:'u'+Date.now()+Math.random(),title:f.name.replace(/\.[^/.]+$/,'').toUpperCase(),artist:'My Music',album:'Local Library',duration:0,img:refs[0],src:URL.createObjectURL(f),favorite:false,played:0}));renderAll();document.querySelector('[data-lib="uploads"]').click()};$('themeBtn').onclick=()=>document.body.classList.toggle('light');setInterval(()=>{if(!songs[current].src&&demoPlaying){let v=+$('seek').value+1;$('seek').value=v;$('timeNow').textContent=fmt(v);if(v>=songs[current].duration)(repeat?($('seek').value=0):next())}},1000);renderAll();playSong('1',false);audio.volume=.7;demoPlaying=false;updatePlayButtons();

$("editProfile")?.addEventListener("click",()=>{
  const name=prompt("Enter your display name:", "KIS Kishore");
  if(name && name.trim()){
    document.querySelector("#profile .profile-main h1").textContent=name.trim();
    document.querySelector("#profile .profile-photo").textContent=name.trim().charAt(0).toUpperCase();
  }
});
$("shareProfile")?.addEventListener("click",async()=>{
  const text="GK Music profile — KIS Kishore";
  try{await navigator.clipboard.writeText(text);alert("Profile text copied!")}catch(e){alert(text)}
});
$("profileRecent")?.addEventListener("click",()=>{document.querySelector('[data-lib="recent"]')?.click();show("library")});
